@startuml
!startsub DB
participant System
participant DB_API
System -> DB_API : save step
DB_API -> DB_API : save data
alt if successful
    DB_API --> System : return successful response
else failed to save
    DB_API -> DB_API : save step to folder
    DB_API --> System : return successful response
end
!endsub
@enduml