@startuml
!startsub DB
participant System
participant DB_API
System -> DB_API : save step
alt if successful
    DB_API --> System : return successful html codes\n with body in json document response
else failed to save
    DB_API --> System : return error response
    System -> System : save step to folder
end
!endsub
@enduml