@startuml
actor External_API
participant System
participant Transfer_API
database nosql

External_API -> System : Sends request
activate External_API
activate System
System -> System : input validation checks
opt if field map
    System -> System : validation for field map
end
alt if successful validation
    System -> System : convert json to xml
    alt if no exceptions
        System --> Transfer_API : sends xml data
        activate Transfer_API
        activate nosql
        !includesub db.puml!DB
    else exceptions
        System --> External_API : send exception
        !includesub db.puml!DB
    end
else if error
    System --> External_API : Send error
end
Transfer_API --> System : sends xml response
System -> System : convert xml to json
alt if no exceptions
    System --> External_API : sends json response
else exceptions
    System --> External_API : send exception
end
!includesub db.puml!DB
@enduml